apiVersion: v1
kind: Pod
metadata:
  name: tamura-pod   # `kubectl get pod` で表示される名前
spec:
  containers:
  - name: container-tamura    # 表示先が無い名前
    image: "galaxy.val.cs.tut.ac.jp:4999/tamura/inverse_rendering/pytorch1.1.0:1.3"   # 使用するdocker image
    volumeMounts:
    - name: ws-file
      mountPath: /home/tamura  # ws-fileをマウントするpath
    - name: dshm
      mountPath: /dev/shm
    resources:
      limits:
        nvidia.com/gpu: 1   # 使用するGPU枚数
    command: ["sh", "-c", "tail -f /dev/null"]  # Pod生成後，すぐ実行されるコマンド
    workingDir: /home/tamura/   # Podの中に入ると最初にいる場所
  volumes:
  - name: ws-file
    hostPath:
      path: /nas_share/homes/DOMAIN=VAL/tamura    # ws-fileの実際のpath
      type: Directory
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: "2Gi"
  restartPolicy: OnFailure
  imagePullSecrets:
  - name: val-gitlab-tamura    # 承認情報設定時に作った設定名
  nodeSelector:                     # 使用するGPUの設定．記述が場合は自動で割当られる
    accelerator: nvidia-geforce-rtx2080ti
  #  accelerator: nvidia-titan-rtx
  #  accelerator: nvidia-geforce-gtx1080
